const prompt = require(`prompt-sync`)({sigint:true})
let alfabet = prompt(`Masukkan Huruf (A-Z) : `)
if (alfabet === `a`)
    console.log(`Huruf Tersebut Termasuk Huruf Vokal`)
else if (alfabet === `i`)
    console.log(`Huruf Tersebut Termasuk Huruf Vokal`)
else if (alfabet === `u`)
    console.log(`Huruf Tersebut Termasuk Huruf Vokal`)
else if (alfabet === `e`)
    console.log(`Huruf Tersebut Termasuk Huruf Vokal`)
else if (alfabet === `o`)
    console.log(`Huruf Tersebut Termasuk Huruf Vokal`)
else
    console.log(`Huruf Tersebut Termasuk Konsonan`)