const prompt = require(`prompt-sync`)({sigint:true})
let x = Number(prompt(`Nilai x : `))
let y = Number(prompt(`Nilai y : `))
let z = Number(prompt(`Nilai z : `))
if (x  >= y  && z <= x)
    console.log(`Nilai terbesar adalah X`)
else if (y > x && z < y)
    console.log(`Nilai terbesar adalah Y`)
else if (z > x && y < z)
    console.log(`Nilai terbesar adalah Z`)
else
    console.log(`Ketiganya Memiliki Nilai Sama Besar`)